server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/trusta-market/config-repo.git
          default-label: develop
          search-paths: '{application}'
          clone-on-start: true
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: health, info
